name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile_industry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Industry CV Compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: main.tex
          working_directory: industry
          
      - uses: actions/upload-artifact@master
        with:
          name: industry_cv
          path: industry/main.pdf

  
  compile_academic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Academic CV Compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: main.tex
          working_directory: academic
      - uses: actions/upload-artifact@master
        with:
          name: academic_cv
          path: academic/main.pdf


  commit_compiled:
    runs-on: ubuntu-latest
    needs: [compile_industry, compile_academic]
    steps:
      - uses: actions/checkout@v2
      - name: Download Academic CV
      - uses: actions/download-artifact@master
        with:
          name: academic_cv
          path: academic
      - name: Download Industry CV
      - uses: actions/download-artifact@master
        with:
          name: industry_cv
          path: industry
      - name: Add and Commit
        uses: EndBug/add-and-commit@v7.4.0
        with:
          add: '*/main.pdf --force'
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'Compiled'
     
